### ISSUE TITLE
Compatibility with Arduino 1.6? 

### ISSUE THREAD

**Issue by mixographer** [fricklr/TeeOnArdu#1]
Hi,

I was wondering if this core will work with Arduino 1.6. I see that Paul has released a beta of Teensy that works on 1.6. I'm hoping this core will work in 1.6 also. 

Thanks

**Comment by mixographer** [comment]
I can get the menus to show up by modifying the boards.txt, but I cannot get the examples to compile. The compiler can't find the definition of usbMIDI()

AnalogControlChange.ino:42:7: error: 'usbMIDI' was not declared in this scope

I'll post a diff of my boards.txt

**Comment by fricklr** [comment]
sorry, I didn't work with 1.6 until now.
it's just a little change in platform.txt - you have to add  -D{build.usbtype} to the recipes
cheers

**Comment by mixographer** [comment]
Ok thanks, I'll take a look. Interestingly I was just looking at this again today.
